/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visoes;

/**
 *
 * @author igor_
 */
public class InterfaceOpcoesConsulta extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceOpcoesConsulta
     */
    public InterfaceOpcoesConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelOpcoesConsulta = new javax.swing.JPanel();
        jButtonCriarConsulta = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saúde & Cia - Menu Consultas");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelOpcoesConsulta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanelOpcoesConsulta.setName("jPanelOpcoesConsulta"); // NOI18N
        jPanelOpcoesConsulta.setLayout(new java.awt.GridBagLayout());

        jButtonCriarConsulta.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonCriarConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultaMedica.png"))); // NOI18N
        jButtonCriarConsulta.setText("Criar Consulta");
        jButtonCriarConsulta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jButtonCriarConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCriarConsulta.setName("jButtonCriarConsulta"); // NOI18N
        jButtonCriarConsulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCriarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarConsulta(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelOpcoesConsulta.add(jButtonCriarConsulta, gridBagConstraints);

        jButtonVoltar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black));
        jButtonVoltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVoltar.setName("jButtonVoltar"); // NOI18N
        jButtonVoltar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanelOpcoesConsulta.add(jButtonVoltar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(jPanelOpcoesConsulta, gridBagConstraints);
        jPanelOpcoesConsulta.getAccessibleContext().setAccessibleName("PanelOpcoesConsulta");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void criarConsulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarConsulta
        // TODO add your handling code here:
        this.setVisible(false);
        InterfaceCadConsulta interfaceCadConsulta = new InterfaceCadConsulta();
        interfaceCadConsulta.setVisible(true);
    }//GEN-LAST:event_criarConsulta

    private void voltar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar
        // TODO add your handling code here:
        this.setVisible(false);
        InterfacePrincipalADM interfacePrincipal = new InterfacePrincipalADM();
        interfacePrincipal.setVisible(true);
    }//GEN-LAST:event_voltar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceOpcoesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceOpcoesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceOpcoesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceOpcoesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceOpcoesConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarConsulta;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jPanelOpcoesConsulta;
    // End of variables declaration//GEN-END:variables
}
