/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visoes;

import java.text.ParseException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author igor_
 */
public class InterfaceGerenProtPacienteMedico extends javax.swing.JFrame {
    /**
     * Creates new form InterfaceCadConsulta
     */
    public InterfaceGerenProtPacienteMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelProntuarioPaciente = new javax.swing.JPanel();
        jLabelProntuarioPaciente = new javax.swing.JLabel();
        jLabelSintoas = new javax.swing.JLabel();
        jLabelDiagnostico = new javax.swing.JLabel();
        jLabelPrescricaoTratamento = new javax.swing.JLabel();
        jTextFieldPrescricaoTratamento = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jTextFieldSintomas = new javax.swing.JFormattedTextField();
        jTextFieldDiagnostico = new javax.swing.JFormattedTextField();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saúde & Cia - Cadastro de Consulta");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelProntuarioPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanelProntuarioPaciente.setName("jPanelProntuarioPaciente"); // NOI18N
        jPanelProntuarioPaciente.setLayout(new java.awt.GridBagLayout());

        jLabelProntuarioPaciente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelProntuarioPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProntuarioPaciente.setText("Prontuario Paciente");
        jLabelProntuarioPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelProntuarioPaciente.setName("jLabelProntuarioPaciente"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanelProntuarioPaciente.add(jLabelProntuarioPaciente, gridBagConstraints);

        jLabelSintoas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelSintoas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSintoas.setText("Sintomas:");
        jLabelSintoas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelSintoas.setName("jLabelSintoas"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelProntuarioPaciente.add(jLabelSintoas, gridBagConstraints);

        jLabelDiagnostico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelDiagnostico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDiagnostico.setText("Diagnóstico:");
        jLabelDiagnostico.setName("jLabelDiagnostico"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelProntuarioPaciente.add(jLabelDiagnostico, gridBagConstraints);
        jLabelDiagnostico.getAccessibleContext().setAccessibleName("LabelHora");

        jLabelPrescricaoTratamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelPrescricaoTratamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrescricaoTratamento.setText("Prescrição Tratamento:");
        jLabelPrescricaoTratamento.setName("jLabelPrescricaoTratamento"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelProntuarioPaciente.add(jLabelPrescricaoTratamento, gridBagConstraints);
        jLabelPrescricaoTratamento.getAccessibleContext().setAccessibleName("LabelMedico");

        jTextFieldPrescricaoTratamento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldPrescricaoTratamento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPrescricaoTratamento.setName("jTextFieldPrescricaoTratamento"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelProntuarioPaciente.add(jTextFieldPrescricaoTratamento, gridBagConstraints);
        jTextFieldPrescricaoTratamento.getAccessibleContext().setAccessibleName("TextFieldMedico");

        jButtonCadastrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastrar.setName("jButtonCadastrar"); // NOI18N
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelProntuarioPaciente.add(jButtonCadastrar, gridBagConstraints);
        jButtonCadastrar.getAccessibleContext().setAccessibleName("jButtonCriar");

        jTextFieldSintomas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jTextFieldSintomas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSintomas.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jTextFieldSintomas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldSintomas.setName("jTextFieldSintomas"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelProntuarioPaciente.add(jTextFieldSintomas, gridBagConstraints);
        jTextFieldSintomas.getAccessibleContext().setAccessibleName("TextFieldFormatadoData");

        jTextFieldDiagnostico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jTextFieldDiagnostico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDiagnostico.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jTextFieldDiagnostico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldDiagnostico.setName("jTextFieldDiagnostico"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelProntuarioPaciente.add(jTextFieldDiagnostico, gridBagConstraints);
        jTextFieldDiagnostico.getAccessibleContext().setAccessibleName("TextFieldFormatadoHora");

        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelProntuarioPaciente.add(jButtonCancelar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        getContentPane().add(jPanelProntuarioPaciente, gridBagConstraints);
        jPanelProntuarioPaciente.getAccessibleContext().setAccessibleName("CadastroConsulta");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        // TODO add your handling code here:
        this.setVisible(false);
        InterfaceOpcoesConsulta interfaceOpcoesConsulta = new InterfaceOpcoesConsulta();
        interfaceOpcoesConsulta.setVisible(true);
    }//GEN-LAST:event_cancelar

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCadConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelDiagnostico;
    private javax.swing.JLabel jLabelPrescricaoTratamento;
    private javax.swing.JLabel jLabelProntuarioPaciente;
    private javax.swing.JLabel jLabelSintoas;
    private javax.swing.JPanel jPanelProntuarioPaciente;
    private javax.swing.JFormattedTextField jTextFieldDiagnostico;
    private javax.swing.JTextField jTextFieldPrescricaoTratamento;
    private javax.swing.JFormattedTextField jTextFieldSintomas;
    // End of variables declaration//GEN-END:variables
}
