package visoes;

import controle.ControlePessoa;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos.Medico;
import modelos.Paciente;
import static visoes.InterfaceLogin.tipoLogin;

/**
 *
 * @author Igor
 */
public class InterfaceCadMedico extends javax.swing.JFrame {
    /**
     * Creates new form InterfaceCadConsulta
     */
    public InterfaceCadMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCadMedico = new javax.swing.JPanel();
        jLabelNovoMedico = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelCrm = new javax.swing.JLabel();
        jButtonCriar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCrm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saúde & Cia - Cadastro de Paciente");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelCadMedico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanelCadMedico.setName("jPanelCadMedico"); // NOI18N
        jPanelCadMedico.setLayout(new java.awt.GridBagLayout());

        jLabelNovoMedico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNovoMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNovoMedico.setText("Novo Médico:");
        jLabelNovoMedico.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNovoMedico.setName("jLabelNovoMedico"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanelCadMedico.add(jLabelNovoMedico, gridBagConstraints);

        jLabelNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setText("Nome:");
        jLabelNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNome.setName("jLabelNome"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadMedico.add(jLabelNome, gridBagConstraints);

        jLabelCrm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelCrm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCrm.setText("CRM:");
        jLabelCrm.setName("jLabelCrm"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadMedico.add(jLabelCrm, gridBagConstraints);
        jLabelCrm.getAccessibleContext().setAccessibleName("LabelHora");

        jButtonCriar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCriar.setText("Criar");
        jButtonCriar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCriar.setName("jButtonCriar"); // NOI18N
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCadMedico.add(jButtonCriar, gridBagConstraints);
        jButtonCriar.getAccessibleContext().setAccessibleName("jButtonCriar");

        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCadMedico.add(jButtonCancelar, gridBagConstraints);

        jTextFieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNome.setName("jTextFieldNome"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadMedico.add(jTextFieldNome, gridBagConstraints);

        jTextFieldCrm.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCrm.setName("jTextFieldCrm"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadMedico.add(jTextFieldCrm, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        getContentPane().add(jPanelCadMedico, gridBagConstraints);
        jPanelCadMedico.getAccessibleContext().setAccessibleName("CadastroConsulta");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        // TODO add your handling code here:
        this.setVisible(false);
        InterfacePacienteSecretaria interfacePacienteSecretaria = new InterfacePacienteSecretaria();
        interfacePacienteSecretaria.setVisible(true);
    }//GEN-LAST:event_cancelar

    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jButtonCriar){
            Medico medico = new Medico();
            ControlePessoa controlePessoa = new ControlePessoa();

            medico.setNome(jTextFieldNome.getText());
            medico.setCrm(Integer.parseInt(jTextFieldCrm.getText()));
            try {
                controlePessoa.adicionarMedico(medico);
            } catch (IOException ex) {
                Logger.getLogger(InterfaceCadMedico.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "Médico Cadastrado com Sucesso!");
            this.setVisible(false);
            InterfacePrincipalADM interfacePrincipalADM = new InterfacePrincipalADM();
            interfacePrincipalADM.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCadConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JLabel jLabelCrm;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNovoMedico;
    private javax.swing.JPanel jPanelCadMedico;
    private javax.swing.JTextField jTextFieldCrm;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
