package visoes;

import controle.ControlePessoa;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos.Paciente;
import static visoes.InterfaceLogin.tipoLogin;

/**
 *
 * @author Igor
 */
public class InterfaceCadPaciente extends javax.swing.JFrame {
    /**
     * Creates new form InterfaceCadConsulta
     */
    public InterfaceCadPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCadPaciente = new javax.swing.JPanel();
        jLabelNovoPaciente = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelDataNascimento = new javax.swing.JLabel();
        jComboBoxTipoConvenio = new javax.swing.JComboBox<>();
        jLabelTipoConvenio = new javax.swing.JLabel();
        jButtonCriar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldRG = new javax.swing.JTextField();
        jTextFieldFormatadoData = new javax.swing.JFormattedTextField();
        jTextFieldFormatadoCelular = new javax.swing.JFormattedTextField();
        jTextFieldFormatadoTelefone = new javax.swing.JFormattedTextField();
        jTextFieldFormatadoCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saúde & Cia - Cadastro de Paciente");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelCadPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanelCadPaciente.setName("jPanelCadPaciente"); // NOI18N
        jPanelCadPaciente.setLayout(new java.awt.GridBagLayout());

        jLabelNovoPaciente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNovoPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNovoPaciente.setText("Novo Paciente:");
        jLabelNovoPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNovoPaciente.setName("jLabelNovoPaciente"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanelCadPaciente.add(jLabelNovoPaciente, gridBagConstraints);

        jLabelNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setText("Nome:");
        jLabelNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNome.setName("jLabelNome"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelNome, gridBagConstraints);

        jLabelRG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelRG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRG.setText("RG:");
        jLabelRG.setName("jLabelRG"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelRG, gridBagConstraints);
        jLabelRG.getAccessibleContext().setAccessibleName("LabelHora");

        jLabelCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelCPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCPF.setText("CPF:");
        jLabelCPF.setName("jLabelCPF"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelCPF, gridBagConstraints);
        jLabelCPF.getAccessibleContext().setAccessibleName("LabelMedico");

        jLabelDataNascimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelDataNascimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDataNascimento.setText("Data de nascimento:");
        jLabelDataNascimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelDataNascimento.setName("jLabelDataNascimento"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelDataNascimento, gridBagConstraints);
        jLabelDataNascimento.getAccessibleContext().setAccessibleName("LabelPaciente");

        jComboBoxTipoConvenio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxTipoConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Plano de Saúde" }));
        jComboBoxTipoConvenio.setName("jComboBoxTipoConvenio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jComboBoxTipoConvenio, gridBagConstraints);
        jComboBoxTipoConvenio.getAccessibleContext().setAccessibleName("ComboBoxTipoConsulta");

        jLabelTipoConvenio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTipoConvenio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoConvenio.setText("Tipo de convênio:");
        jLabelTipoConvenio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTipoConvenio.setName("jLabelTipoConvenio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 25);
        jPanelCadPaciente.add(jLabelTipoConvenio, gridBagConstraints);

        jButtonCriar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCriar.setText("Criar");
        jButtonCriar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCriar.setName("jButtonCriar"); // NOI18N
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCadPaciente.add(jButtonCriar, gridBagConstraints);
        jButtonCriar.getAccessibleContext().setAccessibleName("jButtonCriar");

        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCadPaciente.add(jButtonCancelar, gridBagConstraints);

        jLabelEndereco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEndereco.setText("Endereço:");
        jLabelEndereco.setName("jLabelEndereco"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelEndereco, gridBagConstraints);

        jLabelCelular.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelCelular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCelular.setText("Celular:");
        jLabelCelular.setName("jLabelCelular"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelCelular, gridBagConstraints);

        jTextFieldEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEndereco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEndereco.setName("jTextFieldEndereco"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldEndereco, gridBagConstraints);

        jLabelEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmail.setText("Email:");
        jLabelEmail.setName("jLabelEmail"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelEmail, gridBagConstraints);

        jLabelTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelefone.setText("Telefone:");
        jLabelTelefone.setName("jLabelTelefone"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelTelefone, gridBagConstraints);

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldEmail.setName("jTextFieldEmail"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldEmail, gridBagConstraints);

        jTextFieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldNome.setName("jTextFieldNome"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldNome, gridBagConstraints);

        jTextFieldRG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldRG.setName("jTextFieldRG"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldRG, gridBagConstraints);

        try {
            jTextFieldFormatadoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFormatadoData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatadoData.setName("jTextFieldFormatadoData"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatadoData, gridBagConstraints);

        try {
            jTextFieldFormatadoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFormatadoCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatadoCelular.setName("jTextFieldFormatadoCelular"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatadoCelular, gridBagConstraints);

        try {
            jTextFieldFormatadoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFormatadoTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatadoTelefone.setName("jTextFieldFormatadoTelefone"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatadoTelefone, gridBagConstraints);

        try {
            jTextFieldFormatadoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.### - ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFormatadoCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatadoCPF, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        getContentPane().add(jPanelCadPaciente, gridBagConstraints);
        jPanelCadPaciente.getAccessibleContext().setAccessibleName("CadastroConsulta");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        // TODO add your handling code here:
        this.setVisible(false);
        InterfacePacienteSecretaria interfacePacienteSecretaria = new InterfacePacienteSecretaria();
        interfacePacienteSecretaria.setVisible(true);
    }//GEN-LAST:event_cancelar

    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jButtonCriar){
            Paciente paciente = new Paciente();
            ControlePessoa controlePessoa = new ControlePessoa();

            paciente.setNome(jTextFieldNome.getText());
            paciente.setCpf(jTextFieldFormatadoCPF.getText());
            paciente.setRg(jTextFieldRG.getText());
            paciente.setDataNascimento(jTextFieldFormatadoData.getText());
            paciente.setEndereco(jTextFieldEndereco.getText());
            paciente.setCelular(jTextFieldFormatadoCelular.getText());
            paciente.setTelefone(jTextFieldFormatadoTelefone.getText());
            paciente.setEmail(jTextFieldEmail.getText());
            paciente.setTipoConvenio(jComboBoxTipoConvenio.getSelectedItem().toString());
            try {
                controlePessoa.adicionarPaciente(paciente);
            } catch (IOException ex) {
                Logger.getLogger(InterfaceCadPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }
            //JOptionPane.showMessageDialog(this, "Paciente Cadastrado com Sucesso!", "Informações", JOptionPane.PLAIN_MESSAGE);
            JOptionPane.showMessageDialog(this, "Paciente Cadastrado com Sucesso!");
            this.setVisible(false);
            InterfacePacienteSecretaria interfacePacienteSecretaria = new InterfacePacienteSecretaria();
            interfacePacienteSecretaria.setVisible(true);
        }
    }//GEN-LAST:event_jButtonCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCadConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JComboBox<String> jComboBoxTipoConvenio;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNovoPaciente;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTipoConvenio;
    private javax.swing.JPanel jPanelCadPaciente;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JFormattedTextField jTextFieldFormatadoCPF;
    private javax.swing.JFormattedTextField jTextFieldFormatadoCelular;
    private javax.swing.JFormattedTextField jTextFieldFormatadoData;
    private javax.swing.JFormattedTextField jTextFieldFormatadoTelefone;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRG;
    // End of variables declaration//GEN-END:variables
}
