/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visoes;

import java.text.ParseException;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author igor_
 */
public class InterfaceCadPaciente extends javax.swing.JFrame {
    /**
     * Creates new form InterfaceCadConsulta
     */
    public InterfaceCadPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCadPaciente = new javax.swing.JPanel();
        jLabelNovoPaciente = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jLabelDataNascimento = new javax.swing.JLabel();
        jTextFieldDataNascimento = new javax.swing.JTextField();
        jComboBoxTipoConvenio = new javax.swing.JComboBox<>();
        jLabelTipoConvenio = new javax.swing.JLabel();
        jButtonCriar = new javax.swing.JButton();
        jTextFieldFormatadoNome = new javax.swing.JFormattedTextField();
        jTextFieldFormatoRG = new javax.swing.JFormattedTextField();
        jButtonCancelar = new javax.swing.JButton();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldFormatoEndereço = new javax.swing.JTextField();
        jTextFieldFormatoCelular = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jTextFieldFormatoTelefone = new javax.swing.JTextField();
        jTextFieldFormatoEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saúde & Cia - Cadastro de Consulta");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelCadPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanelCadPaciente.setName("jPanelCadPaciente"); // NOI18N
        jPanelCadPaciente.setLayout(new java.awt.GridBagLayout());

        jLabelNovoPaciente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNovoPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNovoPaciente.setText("Novo Paciente:");
        jLabelNovoPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNovoPaciente.setName("jLabelNovoPaciente"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanelCadPaciente.add(jLabelNovoPaciente, gridBagConstraints);

        jLabelNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setText("Nome:");
        jLabelNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNome.setName("jLabelNome"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelNome, gridBagConstraints);

        jLabelRG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelRG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRG.setText("RG:");
        jLabelRG.setName("jLabelRG"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelRG, gridBagConstraints);
        jLabelRG.getAccessibleContext().setAccessibleName("LabelHora");

        jLabelCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelCPF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCPF.setText("CPF:");
        jLabelCPF.setName("jLabelCPF"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelCPF, gridBagConstraints);
        jLabelCPF.getAccessibleContext().setAccessibleName("LabelMedico");

        jTextFieldCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldCPF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCPF.setName("jTextFieldCPF"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldCPF, gridBagConstraints);
        jTextFieldCPF.getAccessibleContext().setAccessibleName("TextFieldMedico");

        jLabelDataNascimento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelDataNascimento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDataNascimento.setText("Data de nascimento:");
        jLabelDataNascimento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelDataNascimento.setName("jLabelDataNascimento"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelDataNascimento, gridBagConstraints);
        jLabelDataNascimento.getAccessibleContext().setAccessibleName("LabelPaciente");

        jTextFieldDataNascimento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldDataNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDataNascimento.setName("jTextFieldDataNascimento"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldDataNascimento, gridBagConstraints);

        jComboBoxTipoConvenio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxTipoConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Plano de Saúde" }));
        jComboBoxTipoConvenio.setName("jComboBoxTipoConvenio"); // NOI18N
        jComboBoxTipoConvenio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoConvenioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jComboBoxTipoConvenio, gridBagConstraints);
        jComboBoxTipoConvenio.getAccessibleContext().setAccessibleName("ComboBoxTipoConsulta");

        jLabelTipoConvenio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTipoConvenio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoConvenio.setText("Tipo de convênio:");
        jLabelTipoConvenio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTipoConvenio.setName("jLabelTipoConvenio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 25);
        jPanelCadPaciente.add(jLabelTipoConvenio, gridBagConstraints);

        jButtonCriar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCriar.setText("Criar");
        jButtonCriar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCriar.setName("jButtonCriar"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCadPaciente.add(jButtonCriar, gridBagConstraints);
        jButtonCriar.getAccessibleContext().setAccessibleName("jButtonCriar");

        jTextFieldFormatadoNome.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jTextFieldFormatadoNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatadoNome.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jTextFieldFormatadoNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldFormatadoNome.setName("jTextFieldFormatadoNome"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatadoNome, gridBagConstraints);
        jTextFieldFormatadoNome.getAccessibleContext().setAccessibleName("TextFieldFormatadoData");

        jTextFieldFormatoRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jTextFieldFormatoRG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatoRG.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jTextFieldFormatoRG.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldFormatoRG.setName("jTextFieldFormatoRG"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatoRG, gridBagConstraints);
        jTextFieldFormatoRG.getAccessibleContext().setAccessibleName("TextFieldFormatadoHora");

        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCadPaciente.add(jButtonCancelar, gridBagConstraints);

        jLabelEndereco.setText("Endereço:");
        jLabelEndereco.setName("jLabelEndereco"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelEndereco, gridBagConstraints);

        jLabelCelular.setText("Celular:");
        jLabelCelular.setName("jLabelCelular"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelCelular, gridBagConstraints);

        jTextFieldFormatoEndereço.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldFormatoEndereço.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatoEndereço.setName("jTextFieldFormatoEndereço"); // NOI18N
        jTextFieldFormatoEndereço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormatoEndereçoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatoEndereço, gridBagConstraints);

        jTextFieldFormatoCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldFormatoCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatoCelular.setName("jTextFieldFormatoCelular"); // NOI18N
        jTextFieldFormatoCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormatoCelularActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatoCelular, gridBagConstraints);

        jLabelEmail.setText("Email:");
        jLabelEmail.setName("jLabelEmail"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelEmail, gridBagConstraints);

        jLabelTelefone.setText("Telefone:");
        jLabelTelefone.setName("jLabelTelefone"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jLabelTelefone, gridBagConstraints);

        jTextFieldFormatoTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldFormatoTelefone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatoTelefone.setName("jTextFieldFormatoTelefone"); // NOI18N
        jTextFieldFormatoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFormatoTelefoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatoTelefone, gridBagConstraints);

        jTextFieldFormatoEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldFormatoEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatoEmail.setName("jTextFieldFormatoEmail"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadPaciente.add(jTextFieldFormatoEmail, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        getContentPane().add(jPanelCadPaciente, gridBagConstraints);
        jPanelCadPaciente.getAccessibleContext().setAccessibleName("CadastroConsulta");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        // TODO add your handling code here:
        this.setVisible(false);
        InterfaceOpcoesConsulta interfaceOpcoesConsulta = new InterfaceOpcoesConsulta();
        interfaceOpcoesConsulta.setVisible(true);
    }//GEN-LAST:event_cancelar

    private void jComboBoxTipoConvenioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoConvenioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoConvenioActionPerformed

    private void jTextFieldFormatoEndereçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormatoEndereçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormatoEndereçoActionPerformed

    private void jTextFieldFormatoCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormatoCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormatoCelularActionPerformed

    private void jTextFieldFormatoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFormatoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFormatoTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCadConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JComboBox<String> jComboBoxTipoConvenio;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelDataNascimento;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNovoPaciente;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTipoConvenio;
    private javax.swing.JPanel jPanelCadPaciente;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldDataNascimento;
    private javax.swing.JFormattedTextField jTextFieldFormatadoNome;
    private javax.swing.JTextField jTextFieldFormatoCelular;
    private javax.swing.JTextField jTextFieldFormatoEmail;
    private javax.swing.JTextField jTextFieldFormatoEndereço;
    private javax.swing.JFormattedTextField jTextFieldFormatoRG;
    private javax.swing.JTextField jTextFieldFormatoTelefone;
    // End of variables declaration//GEN-END:variables
}
