/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visoes;

import javax.swing.JOptionPane;

/**
 *
 * @author igor_
 */
public class InterfaceLogin extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceLogin
     */
    public InterfaceLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jPanelLogin = new javax.swing.JPanel();
        jLabelLogoLogin = new javax.swing.JLabel();
        jLabelTxtLogin = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabelTxtSenha = new javax.swing.JLabel();
        jPswFieldSenha = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonImagemSaudeeCia = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saúde & Cia - Login");
        setName("InterfaceLogin"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelLogin.setName("PainelLogin"); // NOI18N
        jPanelLogin.setLayout(new java.awt.GridBagLayout());

        jLabelLogoLogin.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabelLogoLogin.setForeground(new java.awt.Color(0, 204, 204));
        jLabelLogoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saudeECiaRascunho.png"))); // NOI18N
        jLabelLogoLogin.setText("Clínica Médica Saúde & Cia");
        jLabelLogoLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelLogoLogin.setName("jLabelLogoLogin"); // NOI18N
        jLabelLogoLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanelLogin.add(jLabelLogoLogin, gridBagConstraints);

        jLabelTxtLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTxtLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTxtLogin.setText("Login");
        jLabelTxtLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTxtLogin.setName("jLabelTxtLogin"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanelLogin.add(jLabelTxtLogin, gridBagConstraints);

        jTextFieldLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldLogin.setName("jTextFieldLogin"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jPanelLogin.add(jTextFieldLogin, gridBagConstraints);
        jTextFieldLogin.getAccessibleContext().setAccessibleName("TextFieldLogin");
        jTextFieldLogin.getAccessibleContext().setAccessibleDescription("");

        jLabelTxtSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTxtSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTxtSenha.setText("Senha");
        jLabelTxtSenha.setName("jLabelTxtSenha"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanelLogin.add(jLabelTxtSenha, gridBagConstraints);

        jPswFieldSenha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPswFieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPswFieldSenha.setName("jPswFieldSenha"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 150;
        jPanelLogin.add(jPswFieldSenha, gridBagConstraints);
        jPswFieldSenha.getAccessibleContext().setAccessibleName("Senha");

        jButtonEntrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEntrar.setName("jButtonEntrar"); // NOI18N
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanelLogin.add(jButtonEntrar, gridBagConstraints);

        jButtonImagemSaudeeCia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saudeECia..png"))); // NOI18N
        jButtonImagemSaudeeCia.setName("jButtonImagemSaudeeCia"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanelLogin.add(jButtonImagemSaudeeCia, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.insets = new java.awt.Insets(97, 140, 103, 160);
        getContentPane().add(jPanelLogin, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar
        // TODO add your handling code here:
        if(evt.getSource() == jButtonEntrar){
            switch (jTextFieldLogin.getText()) {
                case "Administrador":
                    InterfacePrincipalADM interfacePrincipalAdm = new InterfacePrincipalADM();
                    this.setVisible(false);
                    interfacePrincipalAdm.setVisible(true);
                    break;
                case "Secretaria":
                    InterfacePrincipalSecretaria interfacePrincipalSecretaria = new InterfacePrincipalSecretaria();
                    this.setVisible(false);
                    interfacePrincipalSecretaria.setVisible(true);
                    break;
                case "Medico":
                    InterfacePrincipalMedico interfacePrincipalMedico = new InterfacePrincipalMedico();
                    this.setVisible(false);
                    interfacePrincipalMedico.setVisible(true);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Dados Inválidos!\n Digite Novamente!", "Erro!", JOptionPane.ERROR_MESSAGE);
                    break;
            }
        }
    }//GEN-LAST:event_entrar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonImagemSaudeeCia;
    private javax.swing.JLabel jLabelLogoLogin;
    private javax.swing.JLabel jLabelTxtLogin;
    private javax.swing.JLabel jLabelTxtSenha;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPasswordField jPswFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
