/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visoes;

import controle.ControleConsulta;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import modelos.Consulta;
import org.hibernate.NonUniqueObjectException;

/**
 *
 * @author igor_
 */
public class InterfaceCadConsulta extends javax.swing.JFrame {
    /**
     * Creates new form InterfaceCadConsulta
     */
    public InterfaceCadConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelCadConsulta = new javax.swing.JPanel();
        jLabelNovaConsulta = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jLabelMedico = new javax.swing.JLabel();
        jTextFieldMedico = new javax.swing.JTextField();
        jLabelPaciente = new javax.swing.JLabel();
        jTextFieldPaciente = new javax.swing.JTextField();
        jComboBoxTipoConsulta = new javax.swing.JComboBox<>();
        jLabelTipoConsulta = new javax.swing.JLabel();
        jButtonCriar = new javax.swing.JButton();
        jTextFieldFormatadoData = new javax.swing.JFormattedTextField();
        jTextFieldFormatadoHora = new javax.swing.JFormattedTextField();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Saúde & Cia - Cadastro de Consulta");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelCadConsulta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanelCadConsulta.setName("jPanelCadConsulta"); // NOI18N
        jPanelCadConsulta.setLayout(new java.awt.GridBagLayout());

        jLabelNovaConsulta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelNovaConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNovaConsulta.setText("Nova Consulta:");
        jLabelNovaConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNovaConsulta.setName("jLabelNovaConsulta"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 0);
        jPanelCadConsulta.add(jLabelNovaConsulta, gridBagConstraints);

        jLabelData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelData.setText("Data:");
        jLabelData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelData.setName("jLabelData"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadConsulta.add(jLabelData, gridBagConstraints);

        jLabelHora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHora.setText("Hora:");
        jLabelHora.setName("jLabelHora"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadConsulta.add(jLabelHora, gridBagConstraints);
        jLabelHora.getAccessibleContext().setAccessibleName("LabelHora");

        jLabelMedico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelMedico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMedico.setText("Médico:");
        jLabelMedico.setName("jLabelMedico"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadConsulta.add(jLabelMedico, gridBagConstraints);
        jLabelMedico.getAccessibleContext().setAccessibleName("LabelMedico");

        jTextFieldMedico.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldMedico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldMedico.setName("jTextFieldMedico"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadConsulta.add(jTextFieldMedico, gridBagConstraints);
        jTextFieldMedico.getAccessibleContext().setAccessibleName("TextFieldMedico");

        jLabelPaciente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPaciente.setText("Paciente:");
        jLabelPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelPaciente.setName("jLabelPaciente"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadConsulta.add(jLabelPaciente, gridBagConstraints);
        jLabelPaciente.getAccessibleContext().setAccessibleName("LabelPaciente");

        jTextFieldPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPaciente.setName("jTextFieldPaciente"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadConsulta.add(jTextFieldPaciente, gridBagConstraints);

        jComboBoxTipoConsulta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jComboBoxTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal - 1 Hora", "Retorno - 30 Minutos" }));
        jComboBoxTipoConsulta.setName("jComboBoxTipoConsulta"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadConsulta.add(jComboBoxTipoConsulta, gridBagConstraints);
        jComboBoxTipoConsulta.getAccessibleContext().setAccessibleName("ComboBoxTipoConsulta");

        jLabelTipoConsulta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelTipoConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTipoConsulta.setText("Tipo da Consulta:");
        jLabelTipoConsulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelTipoConsulta.setName("jLabelTipoConsulta"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 25);
        jPanelCadConsulta.add(jLabelTipoConsulta, gridBagConstraints);

        jButtonCriar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCriar.setText("Criar");
        jButtonCriar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCriar.setName("jButtonCriar"); // NOI18N
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCadConsulta.add(jButtonCriar, gridBagConstraints);
        jButtonCriar.getAccessibleContext().setAccessibleName("jButtonCriar");

        try {
            jTextFieldFormatadoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFormatadoData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatadoData.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jTextFieldFormatadoData.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldFormatadoData.setName("jTextFieldFormatadoData"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadConsulta.add(jTextFieldFormatadoData, gridBagConstraints);
        jTextFieldFormatadoData.getAccessibleContext().setAccessibleName("TextFieldFormatadoData");

        try {
            jTextFieldFormatadoHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFormatadoHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFormatadoHora.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jTextFieldFormatadoHora.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldFormatadoHora.setName("jTextFieldFormatadoHora"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanelCadConsulta.add(jTextFieldFormatadoHora, gridBagConstraints);
        jTextFieldFormatadoHora.getAccessibleContext().setAccessibleName("TextFieldFormatadoHora");

        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancelar.setName("jButtonCancelar"); // NOI18N
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelCadConsulta.add(jButtonCancelar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        getContentPane().add(jPanelCadConsulta, gridBagConstraints);
        jPanelCadConsulta.getAccessibleContext().setAccessibleName("CadastroConsulta");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar
        // TODO add your handling code here:
        this.setVisible(false);
        InterfaceOpcoesConsulta interfaceOpcoesConsulta = new InterfaceOpcoesConsulta();
        interfaceOpcoesConsulta.setVisible(true);
    }//GEN-LAST:event_cancelar

    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        // TODO add your handling code here:
        Consulta consulta = new Consulta();
        int codMedico, codPaciente;
        String strDataConsulta, strHoraConsulta;
        
        consulta.setTipo(jComboBoxTipoConsulta.getSelectedItem().toString());
        codMedico = Integer.parseInt(jTextFieldMedico.getText());
        codPaciente = Integer.parseInt(jTextFieldPaciente.getText());
        strDataConsulta = jTextFieldFormatadoData.getText();
        strHoraConsulta = jTextFieldFormatadoHora.getText();
        
        ControleConsulta controleConsulta = new ControleConsulta();
        boolean loop=true;
        try {
            controleConsulta.criarConsulta(consulta, codMedico, codPaciente, strDataConsulta, strHoraConsulta);
        } catch (IOException ex) {
            Logger.getLogger(InterfaceCadConsulta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NonUniqueObjectException ex) {
            JOptionPane.showMessageDialog(this, "O médico e o paciente informados já possuem consulta marcada!");
        }
        
        
    }//GEN-LAST:event_jButtonCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceCadConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceCadConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JComboBox<String> jComboBoxTipoConsulta;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelMedico;
    private javax.swing.JLabel jLabelNovaConsulta;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JLabel jLabelTipoConsulta;
    private javax.swing.JPanel jPanelCadConsulta;
    private javax.swing.JFormattedTextField jTextFieldFormatadoData;
    private javax.swing.JFormattedTextField jTextFieldFormatadoHora;
    private javax.swing.JTextField jTextFieldMedico;
    private javax.swing.JTextField jTextFieldPaciente;
    // End of variables declaration//GEN-END:variables
}
